# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d32bf5fd899116ad63e57d1eaeec1ce58f3d75f6089786c8c7474ca0dbf29fe18c9b0a95632d8ebf689f032c4463c8acc47fe4ba6a49e9347302c31217c601f

test:
  secret_key_base: ecc1a9c8631166293d1b3225748ebebbdda42d0de1ae233e49a17b760c23e5e50d94451f82fde388068164eb2b3fdff297ab9ab67ef32914ea9a693118d36533

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
